In [1]:
import numpy as np

Create a null vector of size 10 but the fifth value which is 1.

In [2]:
a = np.zeros(10,dtype=int)
a[5] = 1
a

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

Create a vector with values ranging from 10 to 49.

In [3]:
b = np.random.randint(low=10,high = 49,size = 10)
print(np.size(b))
print(b)

10
[24 44 42 14 47 12 48 35 38 41]


 Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
c = np.random.randint(low=0,high = 8,size = (3,3))
print(np.size(c))
print(c)

9
[[1 2 4]
 [4 5 5]
 [3 7 2]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
e = np.random.randn(10,10)
print(np.min(e))
print(np.max(e))

-3.160395530877012
2.7992082178067625


Create a random vector of size 30 and find the mean value.

In [7]:
f = np.random.randn(30)
np.mean(f)

-0.04232234344679461